version: "3.9"
services:
  postgres:
    container_name: go_bank_postgres
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_go_bank_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - go-bank-network
networks:
  go-bank-network:
    driver: bridge
volumes:
  postgres_go_bank_data:
